### PR TITLE
Update pyms library version and add namespace to env vars

### PR DESCRIPTION
**Pull request by rapejim**
Update pyms library version and add namespace to env vars

### CODE REVIEW

**Review by alexppg — DISMISSED** [review]
The GH checks are failing, please make them pass.

**Comment by rapejim** [comment]
> The GH checks are failing, please make them pass.

Yeah, I will try solve it, ;D

**Comment by avara1986** [comment]
Tip: look in Pipfile @rapejim :stuck_out_tongue:

**Comment by rapejim** [comment]
> Tip: look in Pipfile @rapejim :stuck_out_tongue: 

Thank you for the tip, 👏🏼

**Review by avara1986 — APPROVED** [review]

**Pull request merged**
